baseURL = "https://ponyfest.horse/"
languageCode = "en-us"
title = "PonyFest"
googleAnalytics = "UA-161603031-1"

[params]
  scheduleApiUriDev = "https://schedule-api.ponyfest.horse/schedule"
  scheduleApiUri = "https://schedule-api.ponyfest.horse/schedule"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true
