baseURL = "https://ponyfest.horse/"
languageCode = "en-us"
title = "PonyFest"
googleAnalytics = "UA-161603031-1"

[params]
  scheduleApiUriDev = "https://schedule-api.ponyfest.horse/schedule"
  scheduleApiUri = "https://schedule-api.ponyfest.horse/schedule"
  scheduleInterval = "15"
  scheduleCountdown = "2024-01-27T13:45:00-05:00"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true
