baseURL = "https://ponyfest.horse/"
languageCode = "en-us"
title = "PonyFest"
googleAnalytics = "UA-161603031-1"

[params]
  scheduleApiUriDev = "/schedule.json"
  scheduleApiUri = "/schedule.json"
  scheduleInterval = "5"
  scheduleCountdown = "2023-05-20T21:45:00-04:00"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true
