baseURL = "https://ponyfest.horse/"
languageCode = "en-us"
title = "PonyFest"
googleAnalytics = "UA-161603031-1"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true
