baseURL = "https://ponyfest.horse/"
languageCode = "en-us"
title = "PonyFest"

[params]
  scheduleApiUriDev = "/schedule.json"
  scheduleApiUri = "/schedule.json"
  scheduleInterval = "15"
  scheduleCountdown = "2024-01-27T13:45:00-05:00"
  scheduleTransition = "5"

# this lets use use HTML in our pages if we are so inclined.
[markup.goldmark.renderer]
unsafe = true
